library(shiny)
library(httr)
require(googleVis)
require(data.table)
require(rCharts)
options(RCHART_WIDTH = 800)


shinyServer(
  function(input, output) {
    #Introduction
    output$intro<-renderText({"Bike sharing systems are a means of renting bicycles where the process of obtaining membership, rental, and bike return is automated via a network of kiosk locations throughout a city. Using these systems, people are able rent a bike from a one location and return it to a different place on an as-needed basis. Currently, there are over 500 bike-sharing programs around the world.

The data generated by these systems makes them attractive for researchers because the duration of travel, departure location, arrival location, and time elapsed is explicitly recorded. Bike sharing systems therefore function as a sensor network, which can be used for studying mobility in a city.(From Kaggle)

Related website:    https://www.citibikenyc.com

This application is reading from http://www.citibikenyc.com/stations/json to fetch location, status and current availability for all stations in the New York City bike sharing imitative."
    })
    
    #table
    output$datatable <- renderDataTable({
      stations[, input$show_vars]
    })
    
    #Map
    output$dataMap <- renderGvis({
      stations$loc=paste(stations$latitude, stations$longitude, sep=":")
      M1 <- gvisMap(stations, "loc" , "stationName",
                    options=list(showTip=TRUE, enableScrollWheel=TRUE,
                                 mapType='normal', useMapTypeControl=TRUE,
                                 width=600,height=600))
      return(M1)
    })
    
    #INFO
    output$myInfo <- renderGvis({
        station <- stations[stations$stationName==input$option,]
        number <- as.numeric(input$option2)+1
        nearestStation <- NearestStations(station,stations)
        nearestStation$loc=paste(nearestStation$latitude, nearestStation$longitude, sep=":")
        nearestStation <- nearestStation[with(nearestStation,order(distance)),]
        nearestStation <- nearestStation[c(1:number),]
        
        table <- gvisTable(nearestStation[,
          c("stationName","availableDocks","totalDocks","statusValue","availableBikes")],options=list(width=600))
        
        map <- gvisMap(nearestStation, "loc" , "stationName",
                      options=list(showTip=TRUE, enableScrollWheel=TRUE,
                                   mapType='normal', useMapTypeControl=TRUE,
                                   width=600,height=300))
        return(gvisMerge(table, map))
    })
  }
)